version: "3.8"

services:
  web:
    image: ${DOCKER_NAMESPACE}/canichess-web:latest
    build:
      context: .
      args:
        UID: ${UID:-1000}
        GID: ${GID:-${UID:-1000}}
    volumes:
      - ./log:/rails/log
      - ./storage:/rails/storage
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    environment:
      - DOCKERIZED=yes
      - REDIS_URL=redis://redis-db:6379
      - DATABASE_URL=postgres://root:password@postgres-db/
    secrets:
      - source: RAILS_MASTER_KEY
        target: /rails/config/master.key
    depends_on:
      redis-db:
        condition: service_started
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:16
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/postgres-db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready
      interval: 2s
      timeout: 5s
      retries: 30

  redis-db:
    image: redis

  sidekiq:
    image: ${DOCKER_NAMESPACE}/canichess-sidekiq:latest
    build: .
    command: bundle exec sidekiq
    secrets:
      - RAILS_MASTER_KEY
    environment:
      - RAILS_MASTER_KEY_FILE=/run/secrets/RAILS_MASTER_KEY
      - REDIS_URL=redis://redis-db:6379
      - DATABASE_URL=postgres://root:password@postgres-db/
    depends_on:
      redis-db:
        condition: service_started
      postgres-db:
        condition: service_healthy

secrets:
  RAILS_MASTER_KEY:
    file: ./config/master.key
